### ISSUE TITLE
Revived as state_machines/state_machines-audit_trail

### ISSUE THREAD

**Issue by rosskevin** [wvanbergen/state_machine-audit_trail#34]
Since @seuros took in the code for the old `state_machine` under a new org called `state_machines` to promote keeping these related gems maintained, I talked with him and decided to bring over `wvanbergen/state_machine-audit_trail` into the fold and he agreed.   

The new location is:
https://github.com/state-machines/state_machines-audit_trail

There are some updates/changes, but mostly in name only:

1. converted to use state_machines namespace
1. refactored some naming and options:
    * store_audit_trail is now audit_trail
    * option - `:to` is now `:class`
    * option - `:initial` is an enhancement
    * option - `:context_to_log` is now `:context`
1. improved the readme
1. dropped support for all old versions
1. updated rspec to 3 syntax

I hope that I've provided proper attribution in this process, if I have not, please let me know and I'll correct it immediately.  

Thank you for all the work and I hope you are pleased that others want to carry this work forward.  If you wouldn't mind, a link to the new repo in your README could help boost support for the revived gem.

Cheers

**Comment by wvanbergen** [comment]
Awesome that you want to keep this gem going. 

My suggestion:
- Let's point the README of this repo to the new location.
- Let's release a new major version

Can you provide a rubygems username, so I can give you access to releasing new versions?

**Comment by seuros** [comment]
I think the current gem should be deprecated and include a post install message that warn the user to use the new gem. 

The new gem depend on another set of gems than the current one and require explicit addition of the integration(AR or Mongo).

**Comment by wvanbergen** [comment]
Ah wait, you renamed it (I didn't notice the extra `s`). In that case, feel free to open a PR to update this gem to have a post install message and a new README.

**Comment by rosskevin** [comment]
Pull request added:
https://github.com/wvanbergen/state_machine-audit_trail/pull/35

I linked to some conversion notes in the new wiki.

**Comment by wvanbergen** [comment]
Merged. Feel free to also add a post install message to the gemspec if you want to. I will do a final release after that.

**Comment by rosskevin** [comment]
Just added a message, hopefully it works, I'd wait for it to pass travis first because I did it via web.

Thank you very much!  1.0.1 just released with namespaces and it's working well for me.

**Comment by wvanbergen** [comment]
Thanks. I will do a new release somewhere this week.

**Comment by smudge** [comment]
:+1: Nice to see a revival. We're still on an older version of `state_machine-audit_trail`, but next time we change that code I'll make sure we upgrade. I'll also look through the older issues & pull requests in case there are any that would make for good additions to the new gem.

**Comment by wvanbergen** [comment]
Released version 0.1.9 - closing this issue

**Comment by rosskevin** [comment]
@smudge  I looked through them first.  I included https://github.com/wvanbergen/state_machine-audit_trail/pull/32 and made some other small enhancements.
